from sqlalchemy import Column, String, DateTime, Float, JSON, ForeignKey, Integer, Boolean, Text
from sqlalchemy.orm import relationship, declarative_base
from geoalchemy2 import Geography
import datetime
import uuid

Base = declarative_base()

class Asset(Base):
    __tablename__ = "assets"
    
    id = Column(String, primary_key=True)
    kind = Column(String, nullable=False)
    current_status = Column(String)
    last_heartbeat = Column(DateTime(timezone=True), default=datetime.datetime.utcnow)
    location = Column(Geography(geometry_type="POINT", srid=4326))
    classification_level = Column(String, nullable=False)
    metadata_json = Column(JSON, name="metadata", default={})

class Event(Base):
    __tablename__ = "events"
    
    event_id = Column(String, primary_key=True)
    event_type = Column(String, nullable=False)
    asset_id = Column(String, ForeignKey("assets.id"), nullable=False)
    ts = Column(DateTime(timezone=True), nullable=False)
    geo_point = Column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    classification_level = Column(String, nullable=False)
    confidence_score = Column(Float, nullable=False)
    payload = Column(JSON, nullable=False)
    signature = Column(JSON, nullable=False)

class Telemetry(Base):
    __tablename__ = "telemetry"
    
    ts = Column(DateTime(timezone=True), primary_key=True)
    asset_id = Column(String, primary_key=True)
    parameter = Column(String, primary_key=True)
    value = Column(Float, nullable=False)
    unit = Column(String)
    metadata_json = Column(JSON, name="metadata", default={})

class Alert(Base):
    __tablename__ = "alerts"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    event_id = Column(String, ForeignKey("events.event_id"))
    rule_id = Column(String, nullable=False)
    severity = Column(String, nullable=False)
    description = Column(String)
    is_anomaly = Column(Boolean, default=False)
    human_validated = Column(Boolean, default=False)
    validated_by = Column(String)
    metadata_json = Column(JSON, name="metadata", default={})

class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ts = Column(DateTime(timezone=True), default=datetime.datetime.utcnow)
    actor = Column(String, nullable=False)
    action = Column(String, nullable=False)
    resource_type = Column(String, nullable=False)
    resource_id = Column(String, nullable=False)
    context = Column(JSON, default={})


class IntelligenceProduct(Base):
    """
    Formal intelligence products generated by the ARES brain or fusion engine.
    Types: INTSUM, SITREP, THREATSUM, COA_BRIEF, STRAT_BRIEF
    """
    __tablename__ = "intelligence_products"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    product_type = Column(String, nullable=False)          # INTSUM | SITREP | THREATSUM | ...
    content = Column(Text, nullable=False)                  # Full text of the product
    classification_level = Column(String, nullable=False, default="CONFIDENTIAL")
    source_data = Column(JSON, default={})                  # Input data used to generate
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.datetime.utcnow)
    created_by = Column(String, nullable=False, default="SYSTEM")


class PriorityIntelligenceRequirement(Base):
    """
    Commander's Priority Intelligence Requirements (PIRs).
    Drive collection tasking and focus analysis effort.
    """
    __tablename__ = "priority_intelligence_requirements"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    priority = Column(Integer, nullable=False)              # 1 (highest) – 5 (lowest)
    collection_methods = Column(JSON, default=[])           # ["HUMINT", "SIGINT", ...]
    due_date = Column(DateTime(timezone=True), nullable=True)
    classification_level = Column(String, nullable=False, default="CONFIDENTIAL")
    created_by = Column(String, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.datetime.utcnow)


class SensorSource(Base):
    """
    Registry of active sensor/data sources feeding into SESIS.
    Tracks each sensor's identity, type, and last heartbeat.
    """
    __tablename__ = "sensor_sources"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    sensor_id = Column(String, nullable=False, unique=True)
    sensor_type = Column(String, nullable=False)            # HUMINT | SIGINT | SATINT_SAR | CYBER | ...
    status = Column(String, nullable=False, default="ACTIVE")
    classification_level = Column(String, nullable=False, default="CONFIDENTIAL")
    first_seen = Column(DateTime(timezone=True), nullable=False, default=datetime.datetime.utcnow)
    last_seen = Column(DateTime(timezone=True), nullable=False, default=datetime.datetime.utcnow)
    metadata_json = Column(JSON, name="metadata", default={})


class IntelFusionRecord(Base):
    """
    Audit record of each multi-INT fusion operation.
    Stores the result summary and the fusion confidence score.
    """
    __tablename__ = "intel_fusion_records"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    entity_id = Column(String, nullable=True)               # Primary entity if identified
    fusion_score = Column(Float, nullable=False)
    source_count = Column(Integer, nullable=False, default=0)
    correlated_count = Column(Integer, nullable=False, default=0)
    assessment = Column(JSON, default={})
    classification_level = Column(String, nullable=False, default="CONFIDENTIAL")
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.datetime.utcnow)
